# 透過機器學習預測股市漲跌_系列4_模型投資策略驗證

作者：劉睿哲（臺灣行銷研究特邀作者）、蔡尚宏（臺灣行銷研究特邀作者）、鄭晴文（臺灣行銷研究特邀作者）

[原始資料請見此](https://drive.google.com/file/d/1CXMTc1X1vbpDNyE_rh1S_0D3SpQIyVWc/view?usp=sharing)，下載下來與本ipynb檔案放於同一個資料夾中，再執行下方程式即可。

In [118]:
import pandas as pd
import random
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

In [119]:
df = pd.read_csv('回測.csv', usecols = ['Date', 'Label', 'fluctuation','Prediction'])
df['Date'] = pd.to_datetime(df['Date'])
df

          Date  Label  Prediction  fluctuation
0   2015-01-02      1           1     0.000557
1   2015-01-05      0           1    -0.017936
2   2015-01-06      0           1    -0.007572
3   2015-01-07      1           1     0.012072
4   2015-01-08      1           0     0.017957
..         ...    ...         ...          ...
373 2016-06-27      0           0    -0.012387
374 2016-06-28      1           1     0.012752
375 2016-06-29      1           1     0.013672
376 2016-06-30      1           0     0.012264
377 2016-07-01      1           0     0.001402

[378 rows x 4 columns]

In [120]:
# 模型投資策略:遵從模型建議投資之逐月報酬率
AP = 1
month_r = int(2)
percentage_r = []
for i in range(0,378):
    if df.iloc[i,1] == df.iloc[i, 2]:
        AP = AP * (1 + abs(df.iloc[i,-1]))
    else:
        AP = AP * (1 - abs(df.iloc[i,-1]))
    if month_r == 13: #驗證時間橫跨兩年，故重置month
        month_r = 1
    if df['Date'][i].month == month_r:
        percentage_r.append((AP)-1)
        month_r += 1
        

percentage_r #後續將報酬率資料在excel中進行視覺化處理

[-0.06644301930406504,
 -0.04526689756784297,
 0.00321910477460996,
 -0.015806088514222716,
 0.016282300892181967,
 0.004075346946216696,
 0.04275180915531829,
 -0.054141325588687006,
 0.00877428987491502,
 0.05970548966987099,
 0.09812505273331773,
 0.14613902734371176,
 0.16189701400696954,
 0.24246085615262802,
 0.25752575510896336,
 0.2939362734294271,
 0.3529265911937727,
 0.34691113966122655]

In [114]:
# 隨機投資策略:隨機分配各一半天數為看空(0)及看多(1)
randoms = []
for i in range(189):
    randoms.append(0)
for j in range(189):
    randoms.append(1)
random.shuffle(randoms)
df['Randoms'] = randoms
df

          Date  Label  Prediction  fluctuation  Randoms
0   2015-01-02      1           1     0.000557        1
1   2015-01-05      0           1    -0.017936        0
2   2015-01-06      0           1    -0.007572        1
3   2015-01-07      1           1     0.012072        1
4   2015-01-08      1           0     0.017957        0
..         ...    ...         ...          ...      ...
373 2016-06-27      0           0    -0.012387        0
374 2016-06-28      1           1     0.012752        0
375 2016-06-29      1           1     0.013672        0
376 2016-06-30      1           0     0.012264        0
377 2016-07-01      1           0     0.001402        0

[378 rows x 5 columns]

In [115]:
#隨機投資策略:計算逐月報酬率
num = 1
percentage = []
month = int(2)
for i in range(len(df)):
    if df['Randoms'][i] == 0: #隨機猜測做空
        if df['fluctuation'][i] > 0:
            num = num * (1 - (df['fluctuation'][i]/100))
        else:
            num = num * (1 - (df['fluctuation'][i]/100))
    if df['Randoms'][i] == 1: #隨機猜測做多
        if df['fluctuation'][i] > 0:
            num = num * (1 + (df['fluctuation'][i]/100))
        else:
            num = num * (1 + (df['fluctuation'][i]/100))
    if month == 13: #驗證時間橫跨兩年，故重置month
        month = 1
    if df['Date'][i].month == month:
        percentage.append(num)
        month += 1
        
for i in range(len(percentage)):
    percentage[i] = percentage[i].round(4)
    percentage[i] = (percentage[i] - 1)*100

percentage #後續將報酬率資料在excel中進行視覺化處理

[0.029999999999996696,
 0.08999999999999009,
 0.06999999999999229,
 0.09999999999998899,
 0.08999999999999009,
 0.039999999999995595,
 0.05999999999999339,
 0.029999999999996696,
 0.05999999999999339,
 0.07999999999999119,
 0.029999999999996696,
 0.039999999999995595,
 0.05999999999999339,
 0.06999999999999229,
 0.06999999999999229,
 0.06999999999999229,
 -0.009999999999998899,
 -0.019999999999997797]